#!/bin/bash

KUBECONFIGS=~/.kube-configs/
KUBECONFIG=~/.kube/config

if [ ! -d $KUBECONFIGS ]; then
    mkdir $KUBECONFIGS;
fi

if [ $# -lt 1 ]; then 
    echo "Usage: kubeconfig-loader [ls | use | add] <config-name> [<config-content>]"
    exit 1
fi

CMD=$1
CONFIG_NAME=$2

case $CMD in 
    "ls")
        ls -1 $KUBECONFIGS
    ;;
    "use")
        if [ $# -eq 2 ]; then 
            echo "Usage: kubeconfig-loader use <config-name>"
            exit 1
        fi
        if [ ! -f $KUBECONFIGS$CONFIG_NAME ]; then 
            echo "no config found with name '$CONFIG_NAME'"
            exit 1
        fi
        cp $KUBECONFIGS$CONFIG_NAME $KUBECONFIG

    ;;
    "add")
    if [ $# != 3 ]; then
        echo "usage: kubeconfig-loader add <config-name> <config-loader>"
        exit 1
    fi
    CONFIG_FILE=$3
    cat $CONFIG_FILE > "$KUBECONFIGS$CONFIG_NAME"
    echo "added $CONFIG_NAME"
    ;;

    *)
    echo "unknown command $CMD"
    exit 1
    ;;
esac



